version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-acme-pay'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/lib/rabbitmq
networks:
  rabbitmq:
    driver: bridge