version: '3.5'

services:
  postgres-notifications:
    image: postgres
    container_name: acme-pay-notifications-service
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notifications-service
    volumes:
      - "./data/notifications/postgres:/var/lib/postgres/data"
    ports:
      - 5434:5432